# Generated by Django 4.0.5 on 2022-06-08 21:33

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0004_remove_image_likes_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='picture',
            field=cloudinary.models.CloudinaryField(default=1, max_length=255, verbose_name='picture'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_photo',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='profile_photo'),
        ),
    ]
